package freeagent

import (
	"context"
	"net/http"
)

// JournalSet is a balanced set of double-entry journal entries.
//
// See https://dev.freeagent.com/docs/journal_sets
type JournalSet struct {
	URL ResourceURL `json:"url,omitempty"`

	// DatedOn and Description are required, except on the opening balances
	// set which has no date.
	DatedOn     Date   `json:"dated_on,omitzero"`
	Description string `json:"description,omitempty"`
	// Tag marks sets created by your integration. Tagged sets are read-only
	// in the FreeAgent interface, which stops a user editing them out from
	// under you.
	Tag string `json:"tag,omitempty"`

	JournalEntries []JournalEntry `json:"journal_entries,omitempty"`

	// Read-only, and present on the opening balances set only. The
	// documentation types both as bare arrays; they are arrays of objects
	// carrying their own value, not lists of references.
	BankAccounts []JournalSetBalance `json:"bank_accounts,omitempty"`
	StockItems   []JournalSetBalance `json:"stock_items,omitempty"`

	UpdatedAt Time `json:"updated_at,omitzero"`
}

// JournalSetBalance is one opening-balance line for a bank account or a stock
// item, as carried on the opening balances journal set.
type JournalSetBalance struct {
	URL         ResourceURL `json:"url,omitempty"`
	Description string      `json:"description,omitempty"`
	DebitValue  *Decimal    `json:"debit_value,omitempty"`
}

// JournalEntry is one side of a journal set. A negative DebitValue is a
// credit, and a set must balance to zero.
type JournalEntry struct {
	URL ResourceURL `json:"url,omitempty"`
	// Destroy removes the entry on an update.
	Destroy *bool `json:"_destroy,omitempty"`

	// Category and DebitValue are required.
	Category    ResourceURL `json:"category,omitempty"`
	DebitValue  *Decimal    `json:"debit_value,omitempty"`
	Description string      `json:"description,omitempty"`

	// Each of these applies only to the matching category range.
	CapitalAssetType      ResourceURL `json:"capital_asset_type,omitempty"`
	User                  ResourceURL `json:"user,omitempty"`
	StockItem             ResourceURL `json:"stock_item,omitempty"`
	StockAlteringQuantity *int        `json:"stock_altering_quantity,omitempty"`
	BankAccount           ResourceURL `json:"bank_account,omitempty"`
	Property              ResourceURL `json:"property,omitempty"`
	Contact               ResourceURL `json:"contact,omitempty"`
}

// JournalSetService covers https://dev.freeagent.com/docs/journal_sets
type JournalSetService struct {
	Collection[JournalSet]
}

// OpeningBalances returns the account's opening balance journal set, which
// has its own endpoint rather than an id.
//
// It is not an ordinary journal set. It carries no date, and its bank and
// stock legs live in BankAccounts and StockItems rather than in
// JournalEntries, so the entries alone do not sum to zero.
func (s *JournalSetService) OpeningBalances(ctx context.Context) (*JournalSet, *Response, error) {
	req, err := s.client.newRequest(ctx, http.MethodGet, s.meta.Path+"/opening_balances", nil, nil)
	if err != nil {
		return nil, nil, err
	}
	return decodeSingle[JournalSet](s.client, req, s.meta)
}

// Transaction is a posted accounting entry. Transactions are generated by
// FreeAgent from invoices, bills, explanations and journals, so this family
// is read-only.
//
// See https://dev.freeagent.com/docs/transactions
type Transaction struct {
	URL ResourceURL `json:"url,omitempty"`

	DatedOn     Date   `json:"dated_on,omitzero"`
	Description string `json:"description,omitempty"`

	Category     ResourceURL `json:"category,omitempty"`
	CategoryName string      `json:"category_name,omitempty"`
	NominalCode  string      `json:"nominal_code,omitempty"`
	// DebitValue is negative for a credit.
	DebitValue *Decimal `json:"debit_value,omitempty"`
	// SourceItemURL points at whatever produced the entry, such as a bank
	// transaction explanation. It may be absent.
	SourceItemURL ResourceURL `json:"source_item_url,omitempty"`
	// ForeignCurrencyData is an empty object unless foreign currency was
	// involved.
	ForeignCurrencyData *TransactionForeignCurrency `json:"foreign_currency_data,omitempty"`

	CreatedAt Time `json:"created_at,omitzero"`
	UpdatedAt Time `json:"updated_at,omitzero"`
}

// TransactionForeignCurrency carries the original currency amounts.
type TransactionForeignCurrency struct {
	CurrencyCode string   `json:"currency_code,omitempty"`
	DebitValue   *Decimal `json:"debit_value,omitempty"`
}

// TransactionService covers https://dev.freeagent.com/docs/transactions
//
// Note the path: transactions live under accounting/, not at the API root.
//
// The date range is more constrained than the documented 12-month limit
// suggests: it must fall inside a single accounting period. A range that
// starts before the company's first period returns 400 "No accounting period
// includes the specified dates", so derive the bounds from
// Company.AnnualAccountingPeriods rather than from today's date.
type TransactionService struct {
	ReadCollection[Transaction]
}
